// Auto-generated by AKAN Image Optimization Pipeline
// Usage: import { IMAGES } from "@/lib/images"

import blurMapRaw from "@/public/images/blur-map.json";
const blurMap = blurMapRaw as Record<string, { blurDataURL?: string }>;

export interface AkanImage {
  src: string;
  alt: string;
  width: number;
  height: number;
  blurDataURL?: string;
  priority?: boolean;
  sizes?: string;
}

export const IMAGES = {
  AKAN_BODENREINIGUNG_INDUSTRIEHALLE_NACHHER_GLAENZEND: {
    src: "/images/vorher-nachher/akan-bodenreinigung-industriehalle-nachher-glaenzend.webp",
    blurDataURL: blurMap["akan-bodenreinigung-industriehalle-nachher-glaenzend"]?.blurDataURL,
    width: 1200,
    height: 1600,
    priority: true,
  },
  AKAN_BODENREINIGUNG_INDUSTRIEHALLE_VORHER_VERSCHMUTZT: {
    src: "/images/vorher-nachher/akan-bodenreinigung-industriehalle-vorher-verschmutzt.webp",
    blurDataURL: blurMap["akan-bodenreinigung-industriehalle-vorher-verschmutzt"]?.blurDataURL,
    width: 1600,
    height: 1200,
    priority: true,
  },
  AKAN_DECKENVENTILATOR_REINIGUNG_INDUSTRIEHALLE_VORHER: {
    src: "/images/galerie/industriereinigung/akan-deckenventilator-reinigung-industriehalle-vorher.webp",
    blurDataURL: blurMap["akan-deckenventilator-reinigung-industriehalle-vorher"]?.blurDataURL,
    width: 1920,
    height: 1920,
    priority: false,
  },
  AKAN_DECKENVENTILATOR_VERSCHMUTZT_NAHAUFNAHME: {
    src: "/images/galerie/industriereinigung/akan-deckenventilator-verschmutzt-nahaufnahme.webp",
    blurDataURL: blurMap["akan-deckenventilator-verschmutzt-nahaufnahme"]?.blurDataURL,
    width: 1600,
    height: 1200,
    priority: false,
  },
  AKAN_FENSTERREINIGUNG_FENSTERFRONT_KOMPLETT_SAUBER: {
    src: "/images/galerie/fensterreinigung/akan-fensterreinigung-fensterfront-komplett-sauber.webp",
    blurDataURL: blurMap["akan-fensterreinigung-fensterfront-komplett-sauber"]?.blurDataURL,
    width: 1200,
    height: 1600,
    priority: false,
  },
  AKAN_FENSTERREINIGUNG_PANORAMAFENSTER_BERGBLICK_ERGEBNIS: {
    src: "/images/galerie/fensterreinigung/akan-fensterreinigung-panoramafenster-bergblick-ergebnis.webp",
    blurDataURL: blurMap["akan-fensterreinigung-panoramafenster-bergblick-ergebnis"]?.blurDataURL,
    width: 1200,
    height: 1600,
    priority: false,
  },
  AKAN_FENSTERREINIGUNG_TEAM_TELESKOPSTANGE_AKTION: {
    src: "/images/hero/akan-fensterreinigung-team-teleskopstange-aktion.webp",
    blurDataURL: blurMap["akan-fensterreinigung-team-teleskopstange-aktion"]?.blurDataURL,
    width: 1200,
    height: 1600,
    priority: true,
  },
  AKAN_FENSTERREINIGUNG_TERRASSENTUER_SAUBER_NACHHER: {
    src: "/images/galerie/fensterreinigung/akan-fensterreinigung-terrassentuer-sauber-nachher.webp",
    blurDataURL: blurMap["akan-fensterreinigung-terrassentuer-sauber-nachher"]?.blurDataURL,
    width: 1200,
    height: 1600,
    priority: false,
  },
  AKAN_GEWERBEREINIGUNG_GLASFASSADE_GEBAEUDE_AUSSEN: {
    src: "/images/galerie/gewerbereinigung/akan-gewerbereinigung-glasfassade-gebaeude-aussen.webp",
    blurDataURL: blurMap["akan-gewerbereinigung-glasfassade-gebaeude-aussen"]?.blurDataURL,
    width: 1200,
    height: 1600,
    priority: false,
  },
  AKAN_GLASFASSADE_REINIGUNG_GEWERBEGEBAEUDE_EINGANG: {
    src: "/images/hero/akan-glasfassade-reinigung-gewerbegebaeude-eingang.webp",
    blurDataURL: blurMap["akan-glasfassade-reinigung-gewerbegebaeude-eingang"]?.blurDataURL,
    width: 1536,
    height: 1920,
    priority: true,
  },
  AKAN_GLASREINIGUNG_MITARBEITER_BRANDED_HOODIE: {
    src: "/images/galerie/fensterreinigung/akan-glasreinigung-mitarbeiter-branded-hoodie.webp",
    blurDataURL: blurMap["akan-glasreinigung-mitarbeiter-branded-hoodie"]?.blurDataURL,
    width: 1200,
    height: 1600,
    priority: false,
  },
  AKAN_GLASREINIGUNG_PAVILLON_SAUBER_NACHHER: {
    src: "/images/vorher-nachher/akan-glasreinigung-pavillon-sauber-nachher.webp",
    blurDataURL: blurMap["akan-glasreinigung-pavillon-sauber-nachher"]?.blurDataURL,
    width: 1536,
    height: 1920,
    priority: false,
  },
  AKAN_GLASREINIGUNG_WINTERGARTEN_VERSCHMUTZT_VORHER: {
    src: "/images/vorher-nachher/akan-glasreinigung-wintergarten-verschmutzt-vorher.webp",
    blurDataURL: blurMap["akan-glasreinigung-wintergarten-verschmutzt-vorher"]?.blurDataURL,
    width: 1920,
    height: 1536,
    priority: false,
  },
  AKAN_HALLREINIGUNG_STAHLKONSTRUKTION_KRAN_VETTER: {
    src: "/images/hero/akan-hallreinigung-stahlkonstruktion-kran-vetter.webp",
    blurDataURL: blurMap["akan-hallreinigung-stahlkonstruktion-kran-vetter"]?.blurDataURL,
    width: 1200,
    height: 1600,
    priority: true,
  },
  AKAN_INDUSTRIEHALLE_REINIGUNG_KRANANLAGE_PERSPEKTIVE: {
    src: "/images/galerie/industriereinigung/akan-industriehalle-reinigung-krananlage-perspektive.webp",
    blurDataURL: blurMap["akan-industriehalle-reinigung-krananlage-perspektive"]?.blurDataURL,
    width: 1600,
    height: 1200,
    priority: false,
  },
  AKAN_INDUSTRIEREINIGUNG_LUEFTUNGSANLAGE_REMKO_VORHER: {
    src: "/images/galerie/industriereinigung/akan-industriereinigung-lueftungsanlage-remko-vorher.webp",
    blurDataURL: blurMap["akan-industriereinigung-lueftungsanlage-remko-vorher"]?.blurDataURL,
    width: 1536,
    height: 1920,
    priority: false,
  },
  AKAN_INDUSTRIEREINIGUNG_PVC_STREIFENVORHANG_MESSRAUM: {
    src: "/images/galerie/industriereinigung/akan-industriereinigung-pvc-streifenvorhang-messraum.webp",
    blurDataURL: blurMap["akan-industriereinigung-pvc-streifenvorhang-messraum"]?.blurDataURL,
    width: 1920,
    height: 1920,
    priority: false,
  },
  AKAN_INDUSTRIEREINIGUNG_PVC_VORHANG_WERKSTATT_PANORAMA: {
    src: "/images/galerie/industriereinigung/akan-industriereinigung-pvc-vorhang-werkstatt-panorama.webp",
    blurDataURL: blurMap["akan-industriereinigung-pvc-vorhang-werkstatt-panorama"]?.blurDataURL,
    width: 1920,
    height: 1920,
    priority: false,
  },
  AKAN_LUEFTUNGSREINIGUNG_REMKO_AGGREGAT_DETAIL: {
    src: "/images/galerie/industriereinigung/akan-lueftungsreinigung-remko-aggregat-detail.webp",
    blurDataURL: blurMap["akan-lueftungsreinigung-remko-aggregat-detail"]?.blurDataURL,
    width: 1200,
    height: 1600,
    priority: false,
  },
  AKAN_PVC_STREIFENVORHANG_DETAIL_INDUSTRIEMASCHINEN: {
    src: "/images/galerie/industriereinigung/akan-pvc-streifenvorhang-detail-industriemaschinen.webp",
    blurDataURL: blurMap["akan-pvc-streifenvorhang-detail-industriemaschinen"]?.blurDataURL,
    width: 1920,
    height: 1920,
    priority: false,
  },
  AKAN_PVC_STREIFENVORHANG_GEREINIGT_INDUSTRIEANLAGE: {
    src: "/images/galerie/industriereinigung/akan-pvc-streifenvorhang-gereinigt-industrieanlage.webp",
    blurDataURL: blurMap["akan-pvc-streifenvorhang-gereinigt-industrieanlage"]?.blurDataURL,
    width: 1200,
    height: 1600,
    priority: false,
  },
  AKAN_PVC_VORHANG_REINIGUNG_DETAIL_ROTMARKIERUNG: {
    src: "/images/galerie/industriereinigung/akan-pvc-vorhang-reinigung-detail-rotmarkierung.webp",
    blurDataURL: blurMap["akan-pvc-vorhang-reinigung-detail-rotmarkierung"]?.blurDataURL,
    width: 1200,
    height: 1600,
    priority: false,
  },
  AKAN_PVC_VORHANG_REINIGUNG_INDUSTRIEANLAGE_NAHAUFNAHME: {
    src: "/images/galerie/industriereinigung/akan-pvc-vorhang-reinigung-industrieanlage-nahaufnahme.webp",
    blurDataURL: blurMap["akan-pvc-vorhang-reinigung-industrieanlage-nahaufnahme"]?.blurDataURL,
    width: 1920,
    height: 1920,
    priority: false,
  },
  AKAN_TEAM_HUBSTEIGER_DECKENVENTILATOR_REINIGUNG_AKTION: {
    src: "/images/hero/akan-team-hubsteiger-deckenventilator-reinigung-aktion.webp",
    blurDataURL: blurMap["akan-team-hubsteiger-deckenventilator-reinigung-aktion"]?.blurDataURL,
    width: 1200,
    height: 1600,
    priority: true,
  },
  AKAN_WINTERGARTEN_REINIGUNG_ERGEBNIS_INNENANSICHT: {
    src: "/images/galerie/glasreinigung/akan-wintergarten-reinigung-ergebnis-innenansicht.webp",
    blurDataURL: blurMap["akan-wintergarten-reinigung-ergebnis-innenansicht"]?.blurDataURL,
    width: 1536,
    height: 1920,
    priority: false,
  },
} as const;